apiVersion: apps/v1
kind: Deployment
metadata:
  name: canada
  labels:
    app: canada
spec:
  replicas: 1
  selector:
    matchLabels:
      app: canada
  template:
    metadata:
      labels:
        app: canada
    spec:
      containers:
        - name: app
          image: kappu1512/springboot-city-images:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: CITY
              value: "canada"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paris
  labels:
    app: paris
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paris
  template:
    metadata:
      labels:
        app: paris
    spec:
      containers:
        - name: app
          image: kappu1512/springboot-city-images:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: CITY
              value: "paris"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: losangeles
  labels:
    app: losangeles
spec:
  replicas: 1
  selector:
    matchLabels:
      app: losangeles
  template:
    metadata:
      labels:
        app: losangeles
    spec:
      containers:
        - name: app
          image: kappu1512/springboot-city-images:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: CITY
              value: "losangeles"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: newdelhi
  labels:
    app: newdelhi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: newdelhi
  template:
    metadata:
      labels:
        app: newdelhi
    spec:
      containers:
        - name: app
          image: kappu1512/springboot-city-images:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: CITY
              value: "newdelhi"
