apiVersion: v1
kind: Service
metadata:
  name: canada
spec:
  selector:
    app: canada
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: paris
spec:
  selector:
    app: paris
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: losangeles
spec:
  selector:
    app: losangeles
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: newdelhi
spec:
  selector:
    app: newdelhi
  ports:
    - port: 80
      targetPort: 8080
