apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: city-route
spec:
  parentRefs:
  - name: city-gateway

  rules:
  # ---- Canada page ----
  - matches:
    - path:
        type: PathPrefix
        value: /canada
    backendRefs:
    - name: canada
      port: 80

  # ---- Static images (shared) ----
  - matches:
    - path:
        type: PathPrefix
        value: /images
    backendRefs:
    - name: canada
      port: 80

  # ---- Paris ----
  - matches:
    - path:
        type: PathPrefix
        value: /paris
    backendRefs:
    - name: paris
      port: 80

  # ---- Los Angeles ----
  - matches:
    - path:
        type: PathPrefix
        value: /losangeles
    backendRefs:
    - name: losangeles
      port: 80

  # ---- New Delhi ----
  - matches:
    - path:
        type: PathPrefix
        value: /newdelhi
    backendRefs:
    - name: newdelhi
      port: 80
