apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: city-route
  namespace: default
spec:
  parentRefs:
    - name: city-gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /canada
      backendRefs:
        - name: canada
          port: 80
    - matches:
        - path:
            type: PathPrefix
            value: /paris
      backendRefs:
        - name: paris
          port: 80
    - matches:
        - path:
            type: PathPrefix
            value: /losangeles
      backendRefs:
        - name: losangeles
          port: 80
    - matches:
        - path:
            type: PathPrefix
            value: /newdelhi
      backendRefs:
        - name: newdelhi
          port: 80
